<a href="https://colab.research.google.com/github/gudiya-archi/python-Data-Science/blob/main/Numpy_trick_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.sort

# Return a sorted copy of an array

# axis = 0 columns ke liye.....for ascending order ke liye

# axis = 1 rows ke liye ..... for ascending order ke liye

In [38]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [39]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[63, 35, 62, 61],
       [75,  9,  5, 12],
       [46, 86,  2, 44],
       [40, 95, 87, 20],
       [17, 22, 83, 34],
       [ 8, 50, 32, 68]])

In [40]:


np.sort(a)
# -----> ascending order


array([ 1, 10, 15, 20, 30, 40, 41, 49, 54, 54, 74, 78, 81, 86, 94])

In [41]:
np.sort(a)[::-1]
# descending order

array([94, 86, 81, 78, 74, 54, 54, 49, 41, 40, 30, 20, 15, 10,  1])

In [42]:



np.sort (b)
# rows waise sorting hua hai ....
# ascending order mein

array([[35, 61, 62, 63],
       [ 5,  9, 12, 75],
       [ 2, 44, 46, 86],
       [20, 40, 87, 95],
       [17, 22, 34, 83],
       [ 8, 32, 50, 68]])

In [43]:

# agar columns waise sorting karna hai toh
#       ---> axis=0 likhana honga
np.sort(b,axis=0)

array([[ 8,  9,  2, 12],
       [17, 22,  5, 20],
       [40, 35, 32, 34],
       [46, 50, 62, 44],
       [63, 86, 83, 61],
       [75, 95, 87, 68]])

# np.append

# The numpy.append() appends values along the mentioned axis at the end of the array

In [44]:



a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [45]:

# code
np.append(a,200)

array([ 40,  74,  15,  20,  94,  54,  54,  78,  86,  41,  10,  30,   1,
        49,  81, 200])

In [46]:

b

array([[63, 35, 62, 61],
       [75,  9,  5, 12],
       [46, 86,  2, 44],
       [40, 95, 87, 20],
       [17, 22, 83, 34],
       [ 8, 50, 32, 68]])

In [47]:
np.append(b,np.ones((b.shape[0],1)), axis=1)

array([[63., 35., 62., 61.,  1.],
       [75.,  9.,  5., 12.,  1.],
       [46., 86.,  2., 44.,  1.],
       [40., 95., 87., 20.,  1.],
       [17., 22., 83., 34.,  1.],
       [ 8., 50., 32., 68.,  1.]])

In [48]:


np.append(b,np.random.random((b.shape[0],1)), axis=1)


array([[63.        , 35.        , 62.        , 61.        ,  0.95241776],
       [75.        ,  9.        ,  5.        , 12.        ,  0.84100405],
       [46.        , 86.        ,  2.        , 44.        ,  0.76911974],
       [40.        , 95.        , 87.        , 20.        ,  0.67611547],
       [17.        , 22.        , 83.        , 34.        ,  0.1305529 ],
       [ 8.        , 50.        , 32.        , 68.        ,  0.79299121]])




# np.concatenate
# numpy.concatenate() function concatenate a sequence of arrays along an existing axis .
with 2D array

In [49]:
# code

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)


[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [50]:
# concatenate in the form of tuple ()
# rows ke form mein
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
# concatenate in the form of tuple ()
# columns ke form mein
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
# with the help of np.unique() method , we can get the unique values from an array given as parameter in np.unique() method.

In [52]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [53]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims
# with the help of Numpy.expand_dims() method , we can get the expanded dimensions of an array

In [54]:
# code
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [55]:
np.expand_dims(a,axis=0)

array([[40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81]])

In [56]:
np.expand_dims(a,axis=0).shape


(1, 15)

In [57]:
a.shape

(15,)

In [58]:
np.expand_dims(a,axis=1)

array([[40],
       [74],
       [15],
       [20],
       [94],
       [54],
       [54],
       [78],
       [86],
       [41],
       [10],
       [30],
       [ 1],
       [49],
       [81]])

In [59]:
np.expand_dims(a,axis=1).shape

(15, 1)

# np.where
# the numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

In [60]:
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [61]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  4,  5,  6,  7,  8, 14]),)

In [62]:

# replace all values > 50 with 0
# np.where(condition , true , false)
np.where(a>50,0,a)

array([40,  0, 15, 20,  0,  0,  0,  0,  0, 41, 10, 30,  1, 49,  0])

In [63]:
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [64]:
np.where(a%2 == 0, 0 ,a)

array([ 0,  0, 15,  0,  0,  0,  0,  0,  0, 41,  0,  0,  1, 49, 81])

# np.argmax
# the numpy.argmax() function returns indices of the max element of the array in a particular axis .





In [65]:
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [66]:
np.argmax(a)

# sab se bada number print ho jayenga....indices mein


np.int64(4)

In [67]:
b

array([[63, 35, 62, 61],
       [75,  9,  5, 12],
       [46, 86,  2, 44],
       [40, 95, 87, 20],
       [17, 22, 83, 34],
       [ 8, 50, 32, 68]])

In [68]:
np.argmax(b,axis=0)

array([1, 3, 3, 5])

In [69]:
np.argmax(b,axis=1) # axis=1 rows ke liye

array([0, 0, 1, 1, 2, 3])

In [70]:
# np.argmin
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [71]:

np.argmin(a)

np.int64(12)

# np.cumsum
# numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

In [72]:
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [73]:
np.cumsum(a)

array([ 40, 114, 129, 149, 243, 297, 351, 429, 515, 556, 566, 596, 597,
       646, 727])

In [74]:
b

array([[63, 35, 62, 61],
       [75,  9,  5, 12],
       [46, 86,  2, 44],
       [40, 95, 87, 20],
       [17, 22, 83, 34],
       [ 8, 50, 32, 68]])

In [76]:
np.cumsum(b)

array([  63,   98,  160,  221,  296,  305,  310,  322,  368,  454,  456,
        500,  540,  635,  722,  742,  759,  781,  864,  898,  906,  956,
        988, 1056])

In [77]:
np.cumsum(b,axis=0) # columns

array([[ 63,  35,  62,  61],
       [138,  44,  67,  73],
       [184, 130,  69, 117],
       [224, 225, 156, 137],
       [241, 247, 239, 171],
       [249, 297, 271, 239]])

In [78]:
np.cumsum(b,axis=1) # rows

array([[ 63,  98, 160, 221],
       [ 75,  84,  89, 101],
       [ 46, 132, 134, 178],
       [ 40, 135, 222, 242],
       [ 17,  39, 122, 156],
       [  8,  58,  90, 158]])

In [79]:
# np.cumprod
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [80]:
np.cumprod(a)

array([                 40,                2960,               44400,
                    888000,            83472000,          4507488000,
              243404352000,      18985539456000,    1632756393216000,
         66943012121856000,  669430121218560000, 1636159562847248384,
       1636159562847248384, 6384842284676964352,  663390994966667264])

In [82]:
b

array([[63, 35, 62, 61],
       [75,  9,  5, 12],
       [46, 86,  2, 44],
       [40, 95, 87, 20],
       [17, 22, 83, 34],
       [ 8, 50, 32, 68]])

In [81]:
np.cumprod(b)

array([                  63,                 2205,               136710,
                    8339310,            625448250,           5629034250,
                28145171250,         337742055000,       15536134530000,
           1336107569580000,     2672215139160000,   117577466123040000,
        4703098644921600000,  4072513498522761216,  3820536970998745088,
        2623763125136695296,  7710484979904716800,  3609972894517805056,
        4479845065624993792,  4740779641573376000,  1032748985167904768,
       -3702782962733416448, -7808590365212016640,  3971433303159865344])

# np.percentile

# numpy.percentile() function used to compute te nth percentile of the given data(array elements) along the specified axis.

In [83]:
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [84]:
np.percentile(a,50)

np.float64(49.0)

In [85]:
np.percentile(a,75)

np.float64(76.0)

In [87]:
np.percentile(a,100)

np.float64(94.0)

In [88]:
np.percentile(a, 0)

np.float64(1.0)

In [89]:
np.median(a)

np.float64(49.0)

# np.histogram
# numpy has a built-in  numpy.histogram() function which represents the frequency of data distribution in the graphical form .

In [90]:
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [91]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 1, 1, 3, 2, 0, 2, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [92]:
np.histogram(a,bins=[0,50,100])

(array([8, 7]), array([  0,  50, 100]))

# np.corrcoef
# Return pearson product-moment correlation coefficients.

In [93]:
salary = np.array([20000,40000,25000,35000,6000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.65135808],
       [0.65135808, 1.        ]])

# np.isin

# with the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sixes .

In [94]:
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [95]:
items = [10,20,3,40,50,60,70,80,90,100]

np.isin(a,items)


array([ True, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False])

In [97]:
items = [10,20,3,40,50,60,70,80,90,100]

a[np.isin(a,items)]


array([40, 20, 10])

# np.flip

# The numpy.flip() function reverses the order of array elements along the specified axis , preserving the shape of the array.

In [98]:
a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [99]:
np.flip(a)   #   ----> reverse ho jaata hai

array([81, 49,  1, 30, 10, 41, 86, 78, 54, 54, 94, 20, 15, 74, 40])

In [100]:
b

array([[63, 35, 62, 61],
       [75,  9,  5, 12],
       [46, 86,  2, 44],
       [40, 95, 87, 20],
       [17, 22, 83, 34],
       [ 8, 50, 32, 68]])

In [101]:
np.flip(b)

array([[68, 32, 50,  8],
       [34, 83, 22, 17],
       [20, 87, 95, 40],
       [44,  2, 86, 46],
       [12,  5,  9, 75],
       [61, 62, 35, 63]])

In [102]:
np.flip(b,axis=0)

array([[ 8, 50, 32, 68],
       [17, 22, 83, 34],
       [40, 95, 87, 20],
       [46, 86,  2, 44],
       [75,  9,  5, 12],
       [63, 35, 62, 61]])

In [103]:
np.flip(b,axis=1)

array([[61, 62, 35, 63],
       [12,  5,  9, 75],
       [44,  2, 86, 46],
       [20, 87, 95, 40],
       [34, 83, 22, 17],
       [68, 32, 50,  8]])

# np.put

# The numpy.put() function replaces specific elements of an array with given values of p_array . Array indexed works on flattened array

In [104]:
# array ko change karta hai np.put
# aur yeh orignal array ko change karta hai

a

array([40, 74, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [107]:
np.put(a,[0,1],[44,98])

In [108]:
a

array([44, 98, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

# np.delete

# the numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [109]:
a

array([44, 98, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [110]:
# np.delete ----> indices
np.delete(a,0)

array([98, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [111]:
np.delete(a,[0,2,4])

array([98, 20, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

# Set functions

* np.union 1d
* np.intersect 1d
* np.setdiff 1d
* np.setxor 1d
* np.in 1d

In [112]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [117]:
np.intersect1d(m,n)

array([3, 4, 5])

In [118]:
np.setdiff1d(m,n)

array([1, 2])

In [119]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [120]:
np.in1d(m,1)

/tmp/ipykernel_1243/1810059527.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

# np.clip

# numpy.clip() function is used to clip (limit) the values in an array.

In [121]:
a

array([44, 98, 15, 20, 94, 54, 54, 78, 86, 41, 10, 30,  1, 49, 81])

In [123]:
np.clip(a,a_min=25,a_max=75)

array([44, 75, 25, 25, 75, 54, 54, 75, 75, 41, 25, 30, 25, 49, 75])