<a href="https://colab.research.google.com/github/gudiya-archi/python-Data-Science/blob/main/Python_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is numpy ?

Numpy is the fundamental package for scientific computing in python. It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrics) , and an assortment of routines for fast operations on arrays , including mathematical , logical, shape manipulation, sorting , selecting ,I/O , discreate fourier transforms basic linear algebra , basic statistical operations, random simulation and much more .

At the core of the Numpy package, is the ndarray object. this encapsulates n-dimensional arrays of homogeneous data type

# Numpy Arrays Vs Python Sequences

* Numpy array have a fixed size at creation , unlike python lists (which can grow dynamically ). changing the size of an ndarray will create a new array and delete the original .

* the elements in a Numpy array are all required to be of the same data type, and thus will be the same size in memory .

* Numpy array facilitate advanced mathematical and other types of operations on large numbers of data . typically ,such operations are executed more efficiently and with less code than is possible using python's built-in-sequences.

* A growing plethora of scientific and mathematical python-based packages are using Numpy arrays, though these typically support python-sequences input , they convert such input to Numpy arrays prior to processing , and they often output Numpy arrays.

# Creating Numpy Arrays

In [2]:
# np.array

import numpy as np

In [ ]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [ ]:
print (type(a))

<class 'numpy.ndarray'>


In [ ]:
# 2D

b = np.array([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D
c = np.array([[[1,2],[3,5]],[[5,6],[7,8]]])
print (c)

[[[1 2]
  [3 5]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype float

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# dtype boolean

np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [ ]:
# dtype
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
# np.arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
# 2 rows and 5 columns

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.arange(1,11).reshape(5,2)

# 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# np.ones # its used tuple

np.ones((3,4))



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random

np.random.random((3,4))

array([[0.24962837, 0.79506873, 0.09445866, 0.55214655],
       [0.20172151, 0.05449655, 0.07153935, 0.82072875],
       [0.57548984, 0.64074765, 0.54942521, 0.93953389]])

In [ ]:
# np.linspace
np.linspace (-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.linspace
np.linspace (-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
# matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array Attributes

In [3]:
a1 = np.arange(10)

a2 = np.arange(12,dtype=float).reshape(3,4)

a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# ndim

In [ ]:
# ndim ----> number dimensional 1D , 2D , 3D
a1.ndim

1

In [ ]:
a2.ndim

2

In [ ]:
a3.ndim

3

# shape

In [ ]:
# shape

a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
a3.shape

(2, 2, 2)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Size

In [ ]:
# size
a3.size

8

In [ ]:
a2.size

12

In [ ]:
a1.size

10

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

# itemsize

* integer 34 byte 4 bit
* integer 64 byte 8 jaise float leta hai

* float 64 byte 8 bit leta hai

In [ ]:
a1.itemsize


8

In [11]:
a2.itemsize

8

In [10]:
a3.itemsize

8

In [4]:
a1 = np.arange(10,dtype=np.int32)

a2 = np.arange(12,dtype=float).reshape(3,4)

a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a1.itemsize)

print(a2)
print(a2.itemsize)

print(a3)
print(a3.itemsize)

[0 1 2 3 4 5 6 7 8 9]
4
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
8
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
8


In [6]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


# Changing Datatype

In [7]:
# astype
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
a3.dtype

dtype('int64')

In [9]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [12]:
a1 = np.arange(12).reshape(3,4)
a2 = np. arange(12,24).reshape(3,4)

In [13]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
# scalar operations
# arithmetic

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [17]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [18]:
a1 - 2


array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [19]:
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [20]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [21]:
# relational

a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
a2 > 25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [24]:
a2 > 16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [26]:
# vector operations
# arithmetic
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [28]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [29]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [30]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [31]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

# Array functions




In [32]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[85., 58., 15.],
       [40., 11., 42.],
       [65., 62., 77.]])

#  max / min / sum / prod

*   0 ---> columns   and    1 ----> rows

In [33]:
# max / min / sum / prod
# 0 ---> col and 1 ---> row

np.max(a1)


np.float64(85.0)

In [34]:
np.min(a1)

np.float64(11.0)

In [35]:
np.sum(a1)

np.float64(455.0)

In [36]:
np.prod(a1)

np.float64(424068404760000.0)

In [37]:
np.max(a1,axis=0)

array([85., 62., 77.])

In [38]:
np.max(a1,axis=1)

array([85., 42., 77.])

In [39]:
np.prod(a1,axis=0)

array([221000.,  39556.,  48510.])

# mean / median / std / var

In [40]:
np.mean(a1)

np.float64(50.55555555555556)

In [44]:
np.mean(a1,axis=0)

array([63.33333333, 43.66666667, 44.66666667])

In [41]:
np.median(a1)

np.float64(58.0)

In [45]:
np.median(a1,axis=1)

array([58., 40., 65.])

In [42]:
np.std(a1)

np.float64(24.253802043808452)

In [43]:
np.var(a1)

np.float64(588.246913580247)

In [46]:
np.var(a1,axis=1)

array([830.88888889, 200.66666667,  42.        ])

# trigonomoetric functions

In [47]:
np.sin(a1)

array([[-0.17607562,  0.99287265,  0.65028784],
       [ 0.74511316, -0.99999021, -0.91652155],
       [ 0.82682868, -0.7391807 ,  0.99952016]])

# dot product

In [48]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)


In [49]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [51]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [52]:
# log and exponents
a1


array([[85., 58., 15.],
       [40., 11., 42.],
       [65., 62., 77.]])

In [53]:
np.log(a1)

array([[4.44265126, 4.06044301, 2.7080502 ],
       [3.68887945, 2.39789527, 3.73766962],
       [4.17438727, 4.12713439, 4.34380542]])

In [54]:
np.exp(a1)

array([[8.22301271e+36, 1.54553894e+25, 3.26901737e+06],
       [2.35385267e+17, 5.98741417e+04, 1.73927494e+18],
       [1.69488924e+28, 8.43835667e+26, 2.75851345e+33]])

In [56]:
# round / floor / ceil
np.random.random((2,3))

array([[0.01776166, 0.21028896, 0.9503242 ],
       [0.32835296, 0.90844194, 0.15065308]])

In [57]:
np.random.random((2,3))*100

array([[98.04248915, 95.7684696 , 41.95847013],
       [36.94250645,  4.80287455, 23.18086287]])

In [59]:
np.round  (np.random.random((2,3))*100)

array([[31.,  3., 58.],
       [41., 11., 37.]])

In [60]:
np.floor(np.random.random((2,3))*100)

array([[57., 51., 79.],
       [32., 24., 72.]])

In [62]:
np.ceil (np.random.random((2,3))*100)

array([[51., 23., 70.],
       [52., 45., 49.]])