<a href="https://colab.research.google.com/github/gudiya-archi/python-Data-Science/blob/main/Python_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is numpy ?

Numpy is the fundamental package for scientific computing in python. It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrics) , and an assortment of routines for fast operations on arrays , including mathematical , logical, shape manipulation, sorting , selecting ,I/O , discreate fourier transforms basic linear algebra , basic statistical operations, random simulation and much more .

At the core of the Numpy package, is the ndarray object. this encapsulates n-dimensional arrays of homogeneous data type

# Numpy Arrays Vs Python Sequences

* Numpy array have a fixed size at creation , unlike python lists (which can grow dynamically ). changing the size of an ndarray will create a new array and delete the original .

* the elements in a Numpy array are all required to be of the same data type, and thus will be the same size in memory .

* Numpy array facilitate advanced mathematical and other types of operations on large numbers of data . typically ,such operations are executed more efficiently and with less code than is possible using python's built-in-sequences.

* A growing plethora of scientific and mathematical python-based packages are using Numpy arrays, though these typically support python-sequences input , they convert such input to Numpy arrays prior to processing , and they often output Numpy arrays.

# Creating Numpy Arrays

In [1]:
# np.array

import numpy as np

In [13]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [14]:
print (type(a))

<class 'numpy.ndarray'>


In [15]:
# 2D

b = np.array([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [16]:
# 3D
c = np.array([[[1,2],[3,5]],[[5,6],[7,8]]])
print (c)

[[[1 2]
  [3 5]]

 [[5 6]
  [7 8]]]


In [17]:
# dtype float

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [18]:
# dtype boolean

np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [19]:
# dtype
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [20]:
# np.arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [22]:
# with reshape
# 2 rows and 5 columns

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
np.arange(1,11).reshape(5,2)

# 5 rows and 2 columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [27]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [28]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
# np.ones # its used tuple

np.ones((3,4))



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
# np.zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
# np.random

np.random.random((3,4))

array([[0.54508355, 0.22394901, 0.11717064, 0.39034516],
       [0.58945866, 0.02204548, 0.95409512, 0.55460088],
       [0.16254285, 0.47897081, 0.20726783, 0.88091651]])

In [32]:
# np.linspace
np.linspace (-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [33]:
# np.linspace
np.linspace (-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [34]:
# np.identity
# matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array Attributes

In [36]:
a1 = np.arange(10)

a2 = np.arange(12,dtype=float).reshape(3,4)

a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# ndim

In [37]:
# ndim ----> number dimensional 1D , 2D , 3D
a1.ndim

1

In [38]:
a2.ndim

2

In [39]:
a3.ndim

3

# shape

In [40]:
# shape

a1.shape

(10,)

In [41]:
a2.shape

(3, 4)

In [42]:
a3.shape

(2, 2, 2)

In [43]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [45]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Size

In [47]:
# size
a3.size

8

In [48]:
a2.size

12

In [49]:
a1.size

10

In [50]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

# itemsize

* integer 34 byte 4 bit
* integer 64 byte 8 jaise float leta hai

* float 64 byte 8 bit leta hai

In [51]:
a1.itemsize


8

In [52]:
a2.itemsize

8

In [53]:
a3.itemsize

8

In [54]:
a1 = np.arange(10,dtype=np.int32)

a2 = np.arange(12,dtype=float).reshape(3,4)

a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a1.itemsize)

print(a2)
print(a2.itemsize)

print(a3)
print(a3.itemsize)

[0 1 2 3 4 5 6 7 8 9]
4
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
8
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
8


In [55]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


# Changing Datatype

In [56]:
# astype
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
a3.dtype

dtype('int64')

In [58]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [59]:
a1 = np.arange(12).reshape(3,4)
a2 = np. arange(12,24).reshape(3,4)

In [60]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [62]:
# scalar operations
# arithmetic

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [64]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [65]:
a1 - 2


array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [66]:
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [67]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [68]:
# relational

a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [69]:
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
a2 > 25

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [71]:
a2 > 16

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [72]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [74]:
# vector operations
# arithmetic
a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [77]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [79]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [80]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

# Array functions




In [81]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 48., 100.,  60.],
       [ 79.,  61.,  61.],
       [ 32.,  50.,  91.]])

#  max / min / sum / prod

*   0 ---> columns   and    1 ----> rows

In [82]:
# max / min / sum / prod
# 0 ---> col and 1 ---> row

np.max(a1)


np.float64(100.0)

In [83]:
np.min(a1)

np.float64(32.0)

In [84]:
np.sum(a1)

np.float64(582.0)

In [85]:
np.prod(a1)

np.float64(1.23265239552e+16)

In [86]:
np.max(a1,axis=0)

array([ 79., 100.,  91.])

In [87]:
np.max(a1,axis=1)

array([100.,  79.,  91.])

In [88]:
np.prod(a1,axis=0)

array([121344., 305000., 333060.])

# mean / median / std / var

In [89]:
np.mean(a1)

np.float64(64.66666666666667)

In [90]:
np.mean(a1,axis=0)

array([53.        , 70.33333333, 70.66666667])

In [91]:
np.median(a1)

np.float64(61.0)

In [92]:
np.median(a1,axis=1)

array([60., 61., 50.])

In [93]:
np.std(a1)

np.float64(20.428737928059416)

In [94]:
np.var(a1)

np.float64(417.3333333333333)

In [95]:
np.var(a1,axis=1)

array([494.22222222,  72.        , 609.55555556])

# trigonomoetric functions

In [96]:
np.sin(a1)

array([[-0.76825466, -0.50636564, -0.30481062],
       [-0.44411267, -0.96611777, -0.96611777],
       [ 0.55142668, -0.26237485,  0.10598751]])

# dot product

In [97]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)


In [98]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [100]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [102]:
# log and exponents
a1


array([[ 48., 100.,  60.],
       [ 79.,  61.,  61.],
       [ 32.,  50.,  91.]])

In [103]:
np.log(a1)

array([[3.87120101, 4.60517019, 4.09434456],
       [4.36944785, 4.11087386, 4.11087386],
       [3.4657359 , 3.91202301, 4.51085951]])

In [104]:
np.exp(a1)

array([[7.01673591e+20, 2.68811714e+43, 1.14200739e+26],
       [2.03828107e+34, 3.10429794e+26, 3.10429794e+26],
       [7.89629602e+13, 5.18470553e+21, 3.31740010e+39]])

In [105]:
# round / floor / ceil
np.random.random((2,3))

array([[0.6006044 , 0.71636481, 0.7186864 ],
       [0.65885751, 0.70655555, 0.67151915]])

In [106]:
np.random.random((2,3))*100

array([[62.18083719, 46.42705122, 26.85382697],
       [70.58276157, 84.88627785, 71.01333392]])

In [111]:
# round
np.round  (np.random.random((2,3))*100)

array([[58., 95.,  5.],
       [ 1., 75., 35.]])

In [112]:
# floor
np.floor(np.random.random((2,3))*100)

array([[56., 38., 95.],
       [22., 52., 49.]])

In [113]:
# ceil
np.ceil (np.random.random((2,3))*100)

array([[83., 60., 43.],
       [80.,  8., 49.]])

# Indexing and Slicing

In [114]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [115]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [118]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a1[-1] # negative indexing

np.int64(9)

In [120]:
a1[0] # positive indexing

np.int64(0)

In [121]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
# pehle row ko count karte hai then uske baad colunms ko
# suppose mujhe 6 nikal lana hai

#    ----> 6
# 2D
a2[1,2]


np.int64(6)

In [124]:
a2[2,3]

np.int64(11)

In [125]:
a2[1,1]

np.int64(5)

In [126]:
a2[1,0]

np.int64(4)

In [127]:
# 3D
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [128]:
# sab se pehle tum ko batana hai ki yeh konse columns maine hai
# yeh 3D hai then uske baad batana hai 2D hai 0 hai ki 1 rows hai suppose mujhe 5 nikalna hai
# 5 answer aana chahiye

a3[1,0,1]

np.int64(5)

In [129]:
a3[0,1,0]   # answer 2

np.int64(2)

In [130]:
a3[0,1,1]

np.int64(3)

In [131]:
a3[0,0,0]

np.int64(0)

In [132]:
a3[1,1,0]

np.int64(6)

In [133]:
# slicing

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a1[2:5]

array([2, 3, 4])

In [135]:
a1[2:5:2]

array([2, 4])

In [136]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
a2[0,:]

array([0, 1, 2, 3])

In [139]:
a2[:,2]

array([ 2,  6, 10])

In [140]:
a2[2,:]

array([ 8,  9, 10, 11])

In [141]:
a2[:,3]

array([ 3,  7, 11])

In [149]:
# 2D
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [156]:
a2[0:2,2:]

array([[2, 3],
       [6, 7]])

In [157]:
a2[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [163]:
a2[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [164]:
a2[1:,0:2]

array([[4, 5],
       [8, 9]])

In [166]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [184]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [185]:
a2[1:2]

array([[4, 5, 6, 7]])

In [187]:
a2[1:2,0::3]

array([[4, 7]])

In [188]:
# answer :
a2[1]

array([4, 5, 6, 7])

In [189]:
a2[1,::3]

array([4, 7])

In [191]:
# 2 type
a2[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [193]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [194]:
# 3D Array
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [195]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [196]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [198]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [200]:
a3[0,1,:]

array([3, 4, 5])

In [201]:
a3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [202]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [203]:
#
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [208]:
a3[::2,0]

array([[ 0,  1,  2],
       [18, 19, 20]])

In [209]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [213]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [214]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [215]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [216]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [217]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [218]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [219]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
# reshape

In [220]:
# Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [221]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [222]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel

In [223]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [224]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [225]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [226]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [227]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [228]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [229]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [230]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [231]:
np.hstack((a5,a4,a4))

array([[12, 13, 14, 15,  0,  1,  2,  3,  0,  1,  2,  3],
       [16, 17, 18, 19,  4,  5,  6,  7,  4,  5,  6,  7],
       [20, 21, 22, 23,  8,  9, 10, 11,  8,  9, 10, 11]])

In [232]:
# vertical splitting
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [233]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [234]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [235]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting

In [236]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [237]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]